#!/usr/bin/env python3
"""Generate 03_BUILD/sitemap.xml from the pages that actually exist.

Every built page links to /sitemap.xml, so it has to be real. Generating it from
disk rather than maintaining it by hand means it can never advertise a page that
was not built -- which is the usual way a sitemap starts lying.

    python3 tools/make_sitemap.py
"""

from __future__ import annotations

import os
import re
from datetime import date

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.dirname(HERE)
BUILD = os.path.join(PROJECT, "03_BUILD")
ORIGIN = "https://www.svind.co.in"

# Priority by role. The homepage and the money page rank above the rest.
PRIORITY = {
    "/": "1.0",
    "/request-a-quote": "0.9",
}
DEFAULT_PRIORITY = "0.8"


def route_for(rel: str) -> str:
    route = "/" + rel.replace(os.sep, "/")
    if route.endswith("/index.html"):
        route = route[: -len("index.html")]
    elif route.endswith(".html"):
        route = route[: -len(".html")]
    return route or "/"


def canonical_of(path: str) -> str | None:
    """Prefer the page's own declared canonical, so the two cannot disagree."""
    with open(path, encoding="utf-8") as fh:
        m = re.search(r'<link rel="canonical" href="([^"]+)"', fh.read())
    return m.group(1) if m else None


def main() -> None:
    entries: list[tuple[str, str]] = []
    for root, dirs, files in os.walk(BUILD):
        dirs[:] = [d for d in dirs if not d.startswith((".", "assets"))]
        for f in sorted(files):
            if not f.endswith(".html"):
                continue
            path = os.path.join(root, f)
            rel = os.path.relpath(path, BUILD)
            route = route_for(rel)
            url = canonical_of(path) or (ORIGIN + route)
            entries.append((url, PRIORITY.get(route, DEFAULT_PRIORITY)))

    entries.sort(key=lambda e: (-float(e[1]), e[0]))
    today = date.today().isoformat()

    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!-- Generated by tools/make_sitemap.py from the pages present in',
        '     03_BUILD. Do not edit by hand: regenerate after adding a page. -->',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ]
    for url, priority in entries:
        lines += [
            "  <url>",
            f"    <loc>{url}</loc>",
            f"    <lastmod>{today}</lastmod>",
            f"    <priority>{priority}</priority>",
            "  </url>",
        ]
    lines.append("</urlset>")

    dst = os.path.join(BUILD, "sitemap.xml")
    with open(dst, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    print(f"wrote {os.path.relpath(dst, PROJECT)} — {len(entries)} URL(s)")
    for url, priority in entries:
        print(f"  {priority}  {url}")


if __name__ == "__main__":
    main()
